### ISSUE TITLE
Community building around this fork of Notea

### ISSUE THREAD

**Issue by almereyda** [tecc/notea#1]
Now that the upstream repository has been archived, this is the most active fork of the repository since then:

- https://github.com/QingWei-Li/notea/network

It seems advisable to inform the community about this, eventually through reaching out to upstream and adding a note in its Readme.

Then we could reconstruct a shared effort here to bring the code base to new polish together.

What do you think?

Would it even seem advisable to organise a new GitHub organisation, and invite active members from the community over there, in order to establish shared ownership and maintenance of the code base?

**Comment by tecc** [comment]
Hi! Sorry for not responding in a timely manner, I haven't really checked in on GitHub for a while.

I completely agree with your idea; I actually tried to reach out to @QingWei-Li to see if he'd be willing to transfer the project to me since I fully intend on maintaining it (although I suppose I've been slacking a bit - between all my projects, this one had a few smaller issues).
Although, if it were to be transferred to an organisation, what would the name (i.e. username) of that organisation be?  `notea` and `notea-app` are all taken, which is slightly annoying. Perhaps `notea-community`?

**Comment by QingWei-Li** [comment]
Sorry for the late reply. I'm happy to have someone willing to maintain the Notea.

But this project is pretty rough though, and I don't recommend updating on it.
The editor I used before was `rich-markdown-editor`, which also stopped maintenance, so I had to develop an editor or find a replacement.
If all you need is a self-hosted note-taking app, I highly recommend the logeq. In fact, this is the main reason why I stopped maintenance, there is a better alternative.

If you need this Notea name, I can pass it on to you

**Comment by tecc** [comment]
Well, the main reason I am (at least going to attempt) maintaining Notea is that I tried Logseq, and whilst it is no doubt a good note-taking app, personally I prefer Notea as it's centralised/easier to work with on multiple devices.
Also, to clarify: I meant the GitHub username (https://github.com/notea isn't available).

**Comment by corbin-auriti** [comment]
Anything I can do to help? I'd love to see this going again. LogSeq needs instantaneous sync for me to want to use it

**Comment by tecc** [comment]
If you want to help with development, feel free to poke around the [upstream issues](https://github.com/QingWei-Li/notea/issues). That's a massive TODO list there. Otherwise, you could create issues on this repository with features you'd like.
If you're speaking about helping with this specific issue, I'd suppose just participating in it is a good way to help.

Oh, and I completely agree with that LogSeq needs instantaneous\* sync. That's the main dealbreaker for me.

**Comment by tecc** [comment]
@QingWei-Li (and also @almereyda since you might be interested in this) I created an organisation (@notea-org) you could transfer the repository to if you'd like, as that would help with giving it a new home.
Either way, I've created it now.

**Comment by QingWei-Li** [comment]
> @QingWei-Li (and also @almereyda since you might be interested in this) I created an organisation (@notea-org) you could transfer the repository to if you'd like, as that would help with giving it a new home. Either way, I've created it now.

I need org permissions to transfer the repo

**Comment by tecc** [comment]
Sorry, forgot about that. I invited you to the organisation so you can transfer it.

**Comment by tecc** [comment]
So, update on this issue:
Qingwei transferred the repository to @notea-org, so this fork will probably be slightly defunct because of that (beyond my quick experiments with it) - however, this also means that anyone looking for a maintained version now gets redirected to [notea-org/notea](https://github.com/notea-org/notea) (at least for a little while), which will aid in revitalising Notea.
I'm closing this issue now - feel free to comment on notea-org/notea#141, as I will probably do a few touch-ups before merging the PR.

**Comment by almereyda** [comment]
The redirect seems well in place:

![Bildschirmfoto von 2022-09-04 12-10-27](https://user-images.githubusercontent.com/1645308/188308319-ee212d88-b5ef-4c12-8581-13566117f4ae.png)

Very well done everyone.
